M48
; DRILL file {KiCad 9.0.3} date 2025-09-14T12:06:08+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-14T12:06:08+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X40.0Y-33.0
X40.0Y-37.5
X46.5Y-45.5
X46.5Y-49.1
X80.9Y-52.5
X84.5Y-52.5
M30
